# Base configs
baseurl: ""
url: "https://woodyhugh.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Woody Hugh"
subtitle: ""
author: "Woody Hugh"
bio: ""
publicise: ""
web_design: "WH"
social_urls:
  instagram: "https://www.instagram.com/woody.hugh"
  
